// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL6Qqgoks34Ezl_QowM_tsSeiCwYunruc',
    appId: '1:1097515994132:web:0e5561efb8f6127414ab01',
    messagingSenderId: '1097515994132',
    projectId: 'staful-21893',
    authDomain: 'staful-21893.firebaseapp.com',
    storageBucket: 'staful-21893.firebasestorage.app',
    measurementId: 'G-6398MV9X0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnLdazkyB4L1suMEJVzBuoArndzVsbOOw',
    appId: '1:1097515994132:android:08d36083a1da7c1c14ab01',
    messagingSenderId: '1097515994132',
    projectId: 'staful-21893',
    storageBucket: 'staful-21893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhcaIVlpp10e6Tz2VCgR7wFOBQ5ArFUPI',
    appId: '1:1097515994132:ios:1ddb336d46d5459414ab01',
    messagingSenderId: '1097515994132',
    projectId: 'staful-21893',
    storageBucket: 'staful-21893.firebasestorage.app',
    iosBundleId: 'com.example.staful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhcaIVlpp10e6Tz2VCgR7wFOBQ5ArFUPI',
    appId: '1:1097515994132:ios:1ddb336d46d5459414ab01',
    messagingSenderId: '1097515994132',
    projectId: 'staful-21893',
    storageBucket: 'staful-21893.firebasestorage.app',
    iosBundleId: 'com.example.staful',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL6Qqgoks34Ezl_QowM_tsSeiCwYunruc',
    appId: '1:1097515994132:web:b296e018ca03367914ab01',
    messagingSenderId: '1097515994132',
    projectId: 'staful-21893',
    authDomain: 'staful-21893.firebaseapp.com',
    storageBucket: 'staful-21893.firebasestorage.app',
    measurementId: 'G-6EP5ZWW0RR',
  );
}
