final List<Map<String, dynamic>> staffs = [
  {
    "name": "이나라",
    "image": "Ellipse 2.png",
    "workDays": ["sun", "wed", "thu"],
    "workHours": ["09:00", "14:00"],
    "workDate": [],
  },
  {
    "name": "김경민",
    "image": "Ellipse 3.png",
    "workDays": ["sun", "wed", "thu"],
    "workHours": ["09:00", "14:00"],
    "workDate": [],
  },
  {
    "name": "김선미",
    "image": "Ellipse 4.png",
    "workDays": ["sun", "wed", "thu"],
    "workHours": ["09:00", "14:00"],
    "workDate": [],
  },
  {
    "name": "신동찬",
    "image": "Ellipse 5.png",
    "workDays": ["sun", "wed", "thu"],
    "workHours": ["09:00", "14:00"],
    "workDate": [],
  },
  {
    "name": "매니저",
    "image": "Ellipse 2.png",
    "workDays": ["sun", "wed", "thu"],
    "workHours": ["09:00", "14:00"],
    "workDate": [],
  },
  {
    "name": "김수한무거북",
    "image": "Ellipse 3.png",
    "workDays": ["sun", "wed", "thu"],
    "workHours": ["09:00", "14:00"],
    "workDate": [],
  },
  {
    "name": "김수한무",
    "image": "Ellipse 4.png",
    "workDays": ["sun", "wed", "thu"],
    "workHours": ["09:00", "14:00"],
    "workDate": [],
  },
  {
    "name": "Steive Kim",
    "image": "Ellipse 5.png",
    "workDays": ["sun", "wed", "thu"],
    "workHours": ["09:00", "14:00"],
    "workDate": [],
  },
];
